import {
  MAX_AUDIO_BYTES,
  MAX_IMAGE_BYTES,
  MAX_CONTENT_CREDENTIALS_BYTES,
  OPENAI_VERIFY_URL,
  ImageSelectionSchema,
  NormalizedProvenanceResultSchema,
  resultLabel,
  sha256Hex,
  validateImageBytes,
  type CacheSource,
  type ContentCredentials,
  type HistoryRecord,
  type ImageSelection,
} from "@provenance-lens/shared";

import {
  createHistoryRecord,
  verifyRetrievedImage,
} from "../actions/verify-openai-provenance.js";
import {
  createAudioHistoryRecord,
  verifyAudioFile,
} from "../actions/verify-openai-audio.js";
import { getResult, getSettings, replaceHistoryRecord } from "../storage.js";
import {
  API_MODE_REQUIRED_MESSAGE,
  isApiVerificationAuthorized,
} from "../api-verification-policy.js";

const content = required<HTMLElement>("details-content");
const status = required<HTMLElement>("details-status");
const id = new URLSearchParams(location.search).get("id");

void render();

async function render(): Promise<void> {
  if (!id || !isUuid(id)) {
    showError("This result link is invalid.");
    return;
  }
  const record = await getResult(id);
  if (!record) {
    showError("This result is no longer in history.");
    return;
  }
  const settings = await getSettings();
  content.replaceChildren(renderRecord(record, settings.debugMode));
}

function isUuid(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(
    value,
  );
}

function renderRecord(record: HistoryRecord, debugMode = false): HTMLElement {
  const wrapper = document.createElement("div");
  const parsed = NormalizedProvenanceResultSchema.safeParse(record.result);
  if (!parsed.success) {
    showError("The saved result is invalid.");
    return wrapper;
  }
  const result = parsed.data;
  const resultCard = document.createElement("section");
  resultCard.className = `card ${result.verdict === "openai_signal_detected" ? "result-detected" : result.verdict === "no_supported_openai_signal" ? "result-none" : "result-error"}`;
  const heading = document.createElement("h2");
  heading.textContent = resultLabel(result, record.mediaKind);
  const summary = document.createElement("p");
  summary.textContent = result.summary;
  resultCard.append(heading, summary);
  if (result.warnings.length) {
    const warnings = document.createElement("p");
    warnings.className = "muted small";
    warnings.textContent = result.warnings.join(" ");
    resultCard.append(warnings);
  }
  wrapper.append(resultCard);
  if (result.contentCredentials)
    wrapper.append(renderContentCredentials(result.contentCredentials));

  if (debugMode) wrapper.append(renderDebugDetails(result));

  const sourceCard = document.createElement("section");
  sourceCard.className = "card";
  sourceCard.append(headingElement("Check information"));
  sourceCard.append(
    detailsList([
      [
        record.mediaKind === "audio" ? "Source" : "Source website",
        record.sourceHostname || "Unknown",
      ],
      ["Media", record.mediaKind === "audio" ? "Audio" : "Image"],
      ["Page title", record.pageTitle ?? "Not saved"],
      [
        "Input",
        record.inputKind === "screenshot_copy"
          ? "Screenshot copy"
          : "Original retrieved file",
      ],
      ["Check time", formatDate(result.checkedAt)],
      ["Request ID", result.requestId],
      ...(record.cache
        ? ([
            ["Cache", cacheSourceLabel(record.cache.source)],
            ["Cache expiry", formatDate(record.cache.expiresAt)],
          ] as Array<[string, string]>)
        : []),
    ]),
  );
  wrapper.append(sourceCard);

  const signalsCard = document.createElement("section");
  signalsCard.className = "card";
  signalsCard.append(headingElement("Signals"));
  if (!result.signals.length) {
    const none = document.createElement("p");
    none.className = "muted";
    none.textContent = "No applicable signal result was returned.";
    signalsCard.append(none);
  } else {
    const signalList = document.createElement("ul");
    signalList.className = "signal-list";
    for (const signal of result.signals)
      signalList.append(renderSignal(signal));
    signalsCard.append(signalList);
  }
  wrapper.append(signalsCard);

  const limitations = document.createElement("section");
  limitations.className = "card";
  limitations.append(headingElement("What this means"));
  const limitationText = document.createElement("p");
  limitationText.className = "muted small";
  limitationText.textContent =
    record.mediaKind === "audio"
      ? "This checks supported OpenAI audio provenance signals in the exact uploaded file, up to 60 seconds. A missing signal does not prove that audio is human-recorded or that it was not generated by another AI system. Signals can be missing, removed, degraded, or unsupported."
      : "This checks embedded Content Credentials and supported OpenAI provenance signals. A valid signature binds a signed history to this exact file; it does not prove that the depicted scene is true. A missing signal does not prove that an image is human-made. Credentials may be absent or removed, and AI systems may leave no supported signal. Linked remote manifests are not fetched.";
  limitations.append(limitationText);
  wrapper.append(limitations);

  if (record.cache) {
    const recheck = document.createElement("section");
    recheck.className = "card stack";
    recheck.append(headingElement("Recheck"));
    const explanation = document.createElement("p");
    explanation.className = "muted small";
    explanation.textContent =
      "Recheck is an API-only action. It reacquires the exact file locally and uploads it to your configured backend for a new verification. The file must have the same SHA-256 bytes as this result.";
    const button = document.createElement("button");
    button.type = "button";
    button.textContent = "Recheck now";
    const picker = document.createElement("input");
    picker.type = "file";
    picker.accept =
      record.mediaKind === "audio"
        ? ".mp3,.wav,.aac,.flac,.ogg,.opus"
        : "image/png,image/jpeg,image/webp";
    picker.hidden = true;
    picker.addEventListener("change", () => {
      const file = picker.files?.[0];
      if (file) void recheckCachedResult(record, file, button);
      picker.value = "";
    });
    button.addEventListener("click", () => picker.click());
    recheck.append(explanation, button, picker);
    wrapper.append(recheck);
  }

  if (record.manualFallbackAvailable || record.screenshotFallbackAvailable) {
    const fallback = document.createElement("section");
    fallback.className = "card stack";
    fallback.append(headingElement("Fallback options"));
    if (record.manualFallbackAvailable) {
      const manual = document.createElement("p");
      manual.className = "muted small";
      manual.textContent =
        "The exact retrieved image is still available in memory for a manual upload.";
      const download = document.createElement("button");
      download.type = "button";
      download.textContent = "Download selected image";
      download.addEventListener("click", () => {
        void requestDownload(record.id);
      });
      const open = document.createElement("a");
      open.className = "button secondary";
      open.href = OPENAI_VERIFY_URL;
      open.target = "_blank";
      open.rel = "noopener noreferrer";
      open.textContent = "Open OpenAI Verify";
      fallback.append(manual, document.createElement("div"), download, open);
    }
    if (record.screenshotFallbackAvailable) {
      const screenshotText = document.createElement("p");
      screenshotText.className = "muted small";
      screenshotText.textContent =
        "Screenshot fallback is an API-only action. It captures and uploads a screenshot copy to your configured backend. A screenshot can remove metadata or weaken provenance signals, so the result can be less reliable.";
      const screenshot = document.createElement("button");
      screenshot.type = "button";
      screenshot.textContent = "Verify a screenshot copy";
      screenshot.addEventListener("click", () => {
        void chrome.runtime.sendMessage({
          type: "verify-screenshot",
          fallbackId: record.id,
        });
      });
      fallback.append(screenshotText, screenshot);
    }
    wrapper.append(fallback);
  }
  return wrapper;
}

function renderContentCredentials(
  credentials: ContentCredentials,
): HTMLElement {
  const card = document.createElement("section");
  card.className = "card";
  card.append(headingElement("Content Credentials (C2PA)"));
  const statusText = document.createElement("p");
  statusText.textContent =
    credentials.status === "verified"
      ? "The signature and its binding to this exact file verified successfully."
      : credentials.status === "invalid"
        ? "The credentials failed validation. Do not rely on their claims."
        : credentials.status === "not_present"
          ? "No embedded Content Credentials were found. This says nothing about whether AI was used."
          : credentials.validationCodes.includes("c2pa.input.too_large")
            ? `The broader C2PA check supports files up to ${MAX_CONTENT_CREDENTIALS_BYTES / 1024 / 1024} MiB. This file exceeds that limit; the OpenAI result is shown separately.`
            : "The embedded credentials could not be fully checked. Linked remote manifests are not fetched.";
  card.append(statusText);
  if (credentials.status === "verified" || credentials.status === "invalid") {
    card.append(
      detailsList([
        ["Signature", credentials.signatureValid ? "Verified" : "Not verified"],
        [
          "File binding",
          credentials.contentBindingValid ? "Verified" : "Not verified",
        ],
        [
          "Signer trust",
          credentials.signerTrusted
            ? "Trusted by the pinned C2PA trust list"
            : "Not established by the pinned C2PA trust list",
        ],
        ...(credentials.issuer
          ? [
              ["Signing certificate issuer", credentials.issuer] as [
                string,
                string,
              ],
            ]
          : []),
        [
          "AI declaration",
          credentials.aiDeclaration === "generated"
            ? "AI generation declared"
            : credentials.aiDeclaration === "edited"
              ? "AI editing declared"
              : "No supported AI declaration found",
        ],
      ]),
    );
    const note = document.createElement("p");
    note.className = "muted small";
    note.textContent =
      "The certificate issuer identifies the signing credential, not necessarily the creator. An untrusted signer can make a validly signed claim; it is not independently established. Only signed creation or editing actions in the active manifest contribute to the AI declaration.";
    card.append(note);
    if (credentials.actions.length) {
      const label = document.createElement("strong");
      label.textContent = "Signed actions";
      const actions = document.createElement("ul");
      actions.className = "signal-list";
      for (const action of credentials.actions) {
        const item = document.createElement("li");
        item.textContent = `${action.action}${action.digitalSourceType ? ` · ${action.digitalSourceType.split("/").at(-1)}` : ""}`;
        actions.append(item);
      }
      card.append(label, actions);
    }
  }
  return card;
}

function renderDebugDetails(result: HistoryRecord["result"]): HTMLElement {
  const debugCard = document.createElement("section");
  debugCard.className = "card debug-card";
  debugCard.append(headingElement("Debug details (sanitized)"));
  const explanation = document.createElement("p");
  explanation.className = "muted small";
  explanation.textContent =
    "Normalized result fields only; unvalidated provider payloads are never displayed.";
  const pre = document.createElement("pre");
  pre.className = "debug-output";
  pre.textContent = JSON.stringify(result, null, 2);
  debugCard.append(explanation, pre);
  return debugCard;
}

function renderSignal(
  signal: HistoryRecord["result"]["signals"][number],
): HTMLLIElement {
  const item = document.createElement("li");
  item.className = `signal ${signal.outcome === "detected" ? "signal-detected" : "signal-none"}`;
  const title = document.createElement("strong");
  title.textContent = signal.type === "c2pa" ? "C2PA" : "SynthID";
  const outcome = document.createElement("p");
  outcome.textContent =
    signal.outcome === "detected" ? "Detected" : "Not detected";
  item.append(title, outcome);
  const entries: Array<[string, string]> = [];
  if (signal.type === "c2pa" && signal.validationState)
    entries.push([
      "Validation state",
      signal.validationState === "not_present"
        ? "Not present"
        : `${signal.validationState.charAt(0).toUpperCase()}${signal.validationState.slice(1)}`,
    ]);
  if (signal.type === "c2pa" && signal.issuer)
    entries.push(["Issuer", signal.issuer]);
  if (signal.model) entries.push(["Generating model", signal.model]);
  if (signal.generatedAt)
    entries.push(["Generation time", formatDate(signal.generatedAt)]);
  if (entries.length) {
    item.append(detailsList(entries));
  } else {
    const note = document.createElement("p");
    note.className = "muted small";
    note.textContent =
      signal.type === "synthid"
        ? "The API reported this SynthID outcome without model or generation-time metadata."
        : "The API did not provide additional metadata for this signal.";
    item.append(note);
  }
  return item;
}

async function requestDownload(resultId: string): Promise<void> {
  const granted = await chrome.permissions.request({
    permissions: ["downloads"],
  });
  if (!granted) {
    showError("Download permission was not granted.");
    return;
  }
  await chrome.runtime.sendMessage({ type: "download-fallback", resultId });
}

export async function recheckCachedResult(
  record: HistoryRecord,
  file: File,
  button: HTMLButtonElement,
): Promise<void> {
  if (!record.imageSha256) {
    showError("This result has no file hash to recheck.");
    return;
  }
  button.disabled = true;
  status.textContent = "Checking the selected file...";
  status.className = "status";
  let bytes: Uint8Array | null = null;
  try {
    const settings = await getSettings();
    if (!isApiVerificationAuthorized(settings)) {
      showError(API_MODE_REQUIRED_MESSAGE);
      return;
    }
    const maxBytes =
      record.mediaKind === "audio" ? MAX_AUDIO_BYTES : MAX_IMAGE_BYTES;
    if (file.size === 0 || file.size > maxBytes) {
      showError(
        `The selected file is larger than ${maxBytes / 1024 / 1024} MiB or empty.`,
      );
      return;
    }
    bytes = new Uint8Array(await file.arrayBuffer());
    const mime =
      record.mediaKind === "audio"
        ? null
        : validateImageBytes(bytes, file.type);
    const imageSha256 = await sha256Hex(bytes);
    if (imageSha256 !== record.imageSha256) {
      showError("That file does not match the exact bytes from this result.");
      return;
    }
    const verification = mime
      ? {
          mediaKind: "image" as const,
          outcome: await verifyRetrievedImage(
            {
              bytes,
              mime,
              filename: `recheck.${mime === "image/jpeg" ? "jpg" : mime === "image/webp" ? "webp" : "png"}`,
              sourceUrl: "extension-recheck",
            },
            settings,
            { forceRecheck: true },
          ),
        }
      : {
          mediaKind: "audio" as const,
          outcome: await verifyAudioFile(file, settings, {
            forceRecheck: true,
          }),
        };
    const outcome = verification.outcome;
    if (outcome.errorCode || outcome.result.verdict === "indeterminate") {
      showError(outcome.result.summary);
      return;
    }
    const current = await getResult(record.id);
    if (!current) {
      showError("This result is no longer in history.");
      return;
    }
    const replacement =
      verification.mediaKind === "image"
        ? createHistoryRecord(
            recheckSelection(current),
            verification.outcome,
            settings.includePageTitle,
            current.inputKind,
          )
        : createAudioHistoryRecord(verification.outcome);
    const updated: HistoryRecord = { ...replacement, id: current.id };
    if (!(await replaceHistoryRecord(updated))) {
      showError("This result is no longer in history.");
      return;
    }
    await render();
    status.textContent =
      "Recheck completed and the cached result was replaced.";
    status.className = "status success";
  } catch {
    showError(
      record.mediaKind === "audio"
        ? "The selected audio file could not be verified."
        : "The selected file is not a supported PNG, JPEG, or WebP image.",
    );
  } finally {
    bytes?.fill(0);
    button.disabled = false;
  }
}

function recheckSelection(record: HistoryRecord): ImageSelection {
  return ImageSelectionSchema.parse({
    url: "https://extension-recheck.invalid/image",
    sourceKind: "img",
    pageOrigin: "https://extension-recheck.invalid",
    sourceHostname: record.sourceHostname || "unknown",
    pageTitle: record.pageTitle,
    rect: {
      x: 0,
      y: 0,
      width: 1,
      height: 1,
      viewportWidth: 1,
      viewportHeight: 1,
      devicePixelRatio: 1,
    },
  });
}

function detailsList(entries: Array<[string, string]>): HTMLDListElement {
  const list = document.createElement("dl");
  list.className = "details";
  for (const [label, value] of entries) {
    const term = document.createElement("dt");
    term.textContent = label;
    const description = document.createElement("dd");
    description.textContent = value;
    list.append(term, description);
  }
  return list;
}

function headingElement(text: string): HTMLHeadingElement {
  const heading = document.createElement("h2");
  heading.textContent = text;
  return heading;
}

function showError(text: string): void {
  status.textContent = text;
  status.className = "status error";
}

function cacheSourceLabel(source: CacheSource): string {
  if (source === "local_cache") return "Local cache";
  if (source === "server_cache") return "Server cache";
  return "Fresh";
}

function formatDate(value: string): string {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "Unknown" : date.toLocaleString();
}

function required<T extends HTMLElement>(id: string): T {
  const element = document.getElementById(id);
  if (!element) throw new Error(`Missing element: ${id}`);
  return element as T;
}
