export const ACTION_ID = "verify-openai-provenance" as const;
export const AUDIO_ACTION_ID = "verify-openai-audio" as const;
export const DOWNLOAD_ACTION_ID = "download-original-media" as const;
export const MAX_IMAGE_BYTES = 50 * 1024 * 1024;
export const MAX_CONTENT_CREDENTIALS_BYTES = 4 * 1024 * 1024;
// ponytail: 4 MiB bounds parser memory for short compressed audio; raise it only
// after streaming metadata validation and production memory testing exist.
export const MAX_AUDIO_BYTES = 4 * 1024 * 1024;
export const MAX_AUDIO_DURATION_SECONDS = 60;
export const MAX_INLINE_IMAGE_BYTES = 8 * 1024 * 1024;
export const DISCLOSURE_VERSION = 2;
export const DEFAULT_BACKEND_URL = "https://provenance-backend.example.invalid";
export const OPENAI_VERIFY_URL = "https://openai.com/research/verify/";
export const VERIFICATION_POLICY_VERSION = "openai-content-provenance-v1";
export const RESULT_SCHEMA_VERSION = 1;
// The pinned trust snapshot is part of the image policy so old cache entries
// cannot stand in for the broader Content Credentials check.
export const IMAGE_VERIFICATION_POLICY_VERSION =
  "content-provenance-c2pa-6273cdcb4f27-v2";
export const IMAGE_RESULT_SCHEMA_VERSION = 2;
export const DEFAULT_LOCAL_CACHE_LIMIT = 100;
export const DEFAULT_DETECTED_CACHE_TTL_SECONDS = 30 * 24 * 60 * 60;
export const DEFAULT_NO_SIGNAL_CACHE_TTL_SECONDS = 7 * 24 * 60 * 60;
export const INVALID_C2PA_WARNING =
  "A C2PA manifest was present but was invalid. Do not use it as reliable provenance evidence.";
export const NO_SIGNAL_LIMITATION =
  "This does not prove that the image is human-made. Signals can be missing, removed, degraded, or unsupported.";
export const NO_SIGNAL_CACHE_WORDING =
  "No supported OpenAI provenance signal was detected. This does not prove that the image is human-made or that it was not generated by another AI system.";
export const AUDIO_NO_SIGNAL_LIMITATION =
  "This does not prove that the audio is human-recorded. Signals can be missing, removed, degraded, or unsupported.";
export const AUDIO_NO_SIGNAL_CACHE_WORDING =
  "No supported OpenAI audio provenance signal was detected. This does not prove that the audio is human-recorded or that it was not generated by another AI system.";
