import {
  resultLabel,
  type NormalizedProvenanceResult,
  type ResultToastBinding,
} from "@provenance-lens/shared";

export type { ResultToastBinding } from "@provenance-lens/shared";

export function detectedToastCopy(result: NormalizedProvenanceResult): {
  title: string;
  message: string;
} {
  const signals = result.signals
    .filter((signal) => signal.outcome === "detected")
    .map((signal) => (signal.type === "c2pa" ? "C2PA" : "SynthID"));
  return {
    title: "OpenAI provenance detected",
    message: `Detected signals: ${[...new Set(signals)].join(" and ")}.`,
  };
}

export function noSignalToastCopy(result?: NormalizedProvenanceResult): {
  title: string;
  message: string;
} {
  if (
    result?.contentCredentials &&
    result.contentCredentials.status !== "not_present"
  ) {
    return {
      title: resultLabel(result),
      message:
        "See details for signature validation, signer trust, AI declarations and the OpenAI result.",
    };
  }
  return {
    title: "No supported OpenAI signal detected",
    message:
      "This does not prove that the image is human-made or that it was not generated by another AI system.",
  };
}

export function errorToastCopy(reason: string): {
  title: string;
  message: string;
} {
  return {
    title: "Verification failed",
    message: reason,
  };
}

export function matchesResultToastBinding(
  binding: ResultToastBinding,
  request: Pick<ResultToastBinding, "resultId" | "sessionToken">,
  sender: {
    tabId: number | undefined;
    frameId: number | undefined;
    documentId: string | undefined;
  },
): boolean {
  return (
    binding.resultId === request.resultId &&
    binding.sessionToken === request.sessionToken &&
    binding.tabId === sender.tabId &&
    binding.frameId === sender.frameId &&
    binding.documentId === sender.documentId
  );
}

export function sameResultToastBinding(
  left: ResultToastBinding,
  right: ResultToastBinding,
): boolean {
  return matchesResultToastBinding(left, right, {
    tabId: right.tabId,
    frameId: right.frameId,
    documentId: right.documentId,
  });
}

export function upsertResultToastBinding(
  bindings: ResultToastBinding[],
  binding: ResultToastBinding,
  limit: number,
): ResultToastBinding[] {
  return [
    ...bindings.filter(
      (existing) =>
        existing.sessionToken !== binding.sessionToken &&
        (existing.tabId !== binding.tabId ||
          existing.frameId !== binding.frameId ||
          existing.documentId !== binding.documentId),
    ),
    binding,
  ].slice(-limit);
}

export function removeResultToastBinding(
  bindings: ResultToastBinding[],
  binding: ResultToastBinding,
): ResultToastBinding[] {
  return bindings.filter(
    (existing) => !sameResultToastBinding(existing, binding),
  );
}

export function removePageResultToastBindings(
  bindings: ResultToastBinding[],
  page: Pick<ResultToastBinding, "tabId" | "frameId" | "documentId">,
): ResultToastBinding[] {
  return bindings.filter(
    (existing) =>
      existing.tabId !== page.tabId ||
      existing.frameId !== page.frameId ||
      existing.documentId !== page.documentId,
  );
}

export function resultDetailsUrl(
  detailsPageUrl: string,
  resultId: string,
): string {
  const url = new URL(detailsPageUrl);
  url.search = `?id=${encodeURIComponent(resultId)}`;
  url.hash = "";
  return url.toString();
}
