import {
  IMAGE_RESULT_SCHEMA_VERSION,
  IMAGE_VERIFICATION_POLICY_VERSION,
  type CacheMetadata,
  type ExtensionSettings,
  type NormalizedProvenanceResult,
} from "@provenance-lens/shared";

import { findLocalCache, saveLocalCache } from "../../src/cache.js";
import {
  USER_CANCELLED_REASON,
  verifyImageWithBackend,
  verifyRetrievedImage,
  type RetrievedImage,
} from "../../src/actions/verify-openai-provenance.js";

import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("../../src/cache.js", () => ({
  findLocalCache: vi.fn(),
  isCacheableResult: (value: NormalizedProvenanceResult) =>
    value.verdict === "openai_signal_detected" ||
    value.verdict === "no_supported_openai_signal",
  saveLocalCache: vi.fn(),
}));

const requestId = "123e4567-e89b-42d3-a456-426614174000";
const settings: ExtensionSettings = {
  verificationMode: "api" as const,
  acknowledgedVerificationModes: ["api"],
  backendBaseUrl: "https://verify.example",
  clientToken: "client-token",
  historyRetention: 20 as const,
  screenshotFallbackEnabled: false,
  includePageTitle: true,
  debugMode: false,
  localCacheLimit: 100,
  disclosureVersion: 2,
};
const image: RetrievedImage = {
  bytes: new Uint8Array([1, 2, 3]),
  mime: "image/png",
  filename: "image.png",
  sourceUrl: "https://images.example/image.png",
};

function normalized(
  verdict: NormalizedProvenanceResult["verdict"],
): NormalizedProvenanceResult {
  return {
    verdict,
    summary:
      verdict === "openai_signal_detected"
        ? "Detected signals: SynthID."
        : verdict === "no_supported_openai_signal"
          ? "No supported OpenAI provenance signal was detected. This does not prove that the image is human-made or that it was not generated by another AI system."
          : "The image could not be verified.",
    signals:
      verdict === "openai_signal_detected"
        ? [
            {
              type: "synthid",
              outcome: "detected",
              validationState: null,
              issuer: null,
              model: null,
              generatedAt: null,
            },
          ]
        : [],
    warnings: [],
    checkedAt: "2026-09-01T10:00:00.000Z",
    requestId,
    contentCredentials: {
      status: "not_present",
      signatureValid: false,
      contentBindingValid: false,
      signerTrusted: false,
      issuer: null,
      actions: [],
      aiDeclaration: null,
      validationCodes: [],
      trustListVersion: "6273cdcb4f27",
    },
  };
}

function cache(source: CacheMetadata["source"]): CacheMetadata {
  return {
    source,
    originallyCheckedAt: "2026-09-01T10:00:00.000Z",
    expiresAt: "2099-09-08T10:00:00.000Z",
    verificationPolicyVersion: IMAGE_VERIFICATION_POLICY_VERSION,
    resultSchemaVersion: IMAGE_RESULT_SCHEMA_VERSION,
  };
}

function response(
  result: NormalizedProvenanceResult,
  source: CacheMetadata["source"] = "fresh",
): Response {
  return new Response(
    JSON.stringify({
      result,
      cache: result.verdict === "indeterminate" ? null : cache(source),
    }),
    {
      status: 200,
      headers: { "content-type": "application/json" },
    },
  );
}

function miss(): Response {
  return new Response(
    JSON.stringify({
      hit: false,
      verificationPolicyVersion: IMAGE_VERIFICATION_POLICY_VERSION,
    }),
    { status: 200, headers: { "content-type": "application/json" } },
  );
}

function requestUrl(input: RequestInfo | URL): string {
  if (typeof input === "string") return input;
  if (input instanceof URL) return input.toString();
  return input.url;
}

describe("verification cache flow", () => {
  beforeEach(() => {
    vi.mocked(findLocalCache).mockReset();
    vi.mocked(saveLocalCache).mockReset();
    vi.mocked(findLocalCache).mockResolvedValue(null);
  });

  it("returns a local cached result without contacting the backend", async () => {
    const result = normalized("openai_signal_detected");
    vi.mocked(findLocalCache).mockResolvedValue({
      result,
      cache: cache("local_cache"),
    });
    const fetchImpl = vi.fn();

    const outcome = await verifyRetrievedImage(image, settings, {
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    expect(outcome.result).toEqual(result);
    expect(outcome.cache?.source).toBe("local_cache");
    expect(fetchImpl).not.toHaveBeenCalled();
  });

  it("recomputes exact bytes and rejects a stale caller-supplied cache hash", async () => {
    const result = normalized("openai_signal_detected");
    vi.mocked(findLocalCache).mockResolvedValue({
      result,
      cache: cache("local_cache"),
    });
    const fetchImpl = vi.fn();

    const outcome = await verifyRetrievedImage(image, settings, {
      imageSha256: "0".repeat(64),
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    expect(outcome.errorCode).toBe("hash_mismatch");
    expect(outcome.imageSha256).toMatch(/^[a-f0-9]{64}$/u);
    expect(outcome.imageSha256).not.toBe("0".repeat(64));
    expect(findLocalCache).not.toHaveBeenCalled();
    expect(fetchImpl).not.toHaveBeenCalled();
  });

  it("returns a server cache hit without uploading image bytes", async () => {
    const result = normalized("no_supported_openai_signal");
    const fetchImpl = vi.fn<
      (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>
    >(() =>
      Promise.resolve(
        new Response(
          JSON.stringify({
            hit: true,
            result,
            originallyCheckedAt: cache("server_cache").originallyCheckedAt,
            expiresAt: cache("server_cache").expiresAt,
            verificationPolicyVersion: IMAGE_VERIFICATION_POLICY_VERSION,
            resultSchemaVersion: IMAGE_RESULT_SCHEMA_VERSION,
          }),
          { status: 200, headers: { "content-type": "application/json" } },
        ),
      ),
    );

    const outcome = await verifyRetrievedImage(image, settings, {
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    expect(outcome.result).toEqual(result);
    expect(outcome.cache?.source).toBe("server_cache");
    expect(fetchImpl).toHaveBeenCalledTimes(1);
    expect(vi.mocked(saveLocalCache)).toHaveBeenCalledTimes(1);
    const request = fetchImpl.mock.calls[0]?.[1] as RequestInit;
    expect(request.body).toContain("imageSha256");
    expect(request.body).not.toContain("file");
  });

  it.each(["openai_signal_detected", "no_supported_openai_signal"] as const)(
    "uploads and caches a fresh %s result only after a cache miss",
    async (verdict) => {
      const result = normalized(verdict);
      const fetchImpl = vi.fn<
        (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>
      >((input: RequestInfo | URL) =>
        Promise.resolve(
          requestUrl(input).includes("/cache/lookup")
            ? miss()
            : response(result),
        ),
      );

      const outcome = await verifyRetrievedImage(image, settings, {
        fetchImpl: fetchImpl as unknown as typeof fetch,
      });

      expect(outcome.result).toEqual(result);
      expect(outcome.cache?.source).toBe("fresh");
      expect(fetchImpl).toHaveBeenCalledTimes(2);
      expect(vi.mocked(saveLocalCache)).toHaveBeenCalledTimes(1);
      const upload = fetchImpl.mock.calls[1]?.[1] as RequestInit;
      expect(upload.body).toBeInstanceOf(FormData);
      expect((upload.body as FormData).get("imageSha256")).toMatch(
        /^[a-f0-9]{64}$/u,
      );
      expect((upload.body as FormData).get("byteLength")).toBe("3");
    },
  );

  it("does not cache an indeterminate result", async () => {
    const result = normalized("indeterminate");
    const fetchImpl = vi.fn<
      (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>
    >((input: RequestInfo | URL) =>
      Promise.resolve(
        requestUrl(input).includes("/cache/lookup") ? miss() : response(result),
      ),
    );

    const outcome = await verifyRetrievedImage(image, settings, {
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    expect(outcome.errorCode).toBe("invalid_api_response");
    expect(outcome.cache).toBeNull();
    expect(vi.mocked(saveLocalCache)).not.toHaveBeenCalled();
  });

  it("force recheck uses directly supplied file bytes without runtime messaging", async () => {
    const result = normalized("openai_signal_detected");
    const fetchImpl = vi.fn<
      (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>
    >(() => Promise.resolve(response(result)));

    const outcome = await verifyRetrievedImage(image, settings, {
      forceRecheck: true,
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    expect(outcome.cache?.source).toBe("fresh");
    expect(findLocalCache).not.toHaveBeenCalled();
    expect(fetchImpl).toHaveBeenCalledTimes(1);
    const upload = fetchImpl.mock.calls[0]?.[1] as RequestInit;
    expect((upload.body as FormData).get("forceRecheck")).toBe("true");
  });

  it("cancels a streaming backend response when it exceeds 128 KiB without a length header", async () => {
    const oversized = new Uint8Array(128 * 1024 + 1);
    const fetchImpl = vi.fn(() =>
      Promise.resolve(
        new Response(
          new ReadableStream<Uint8Array>({
            start(controller) {
              controller.enqueue(oversized);
              controller.close();
            },
          }),
          {
            status: 200,
            headers: { "content-type": "application/json" },
          },
        ),
      ),
    );

    await expect(
      verifyImageWithBackend(image, settings, {
        fetchImpl: fetchImpl as unknown as typeof fetch,
      }),
    ).rejects.toMatchObject({ code: "invalid_api_response" });
  });

  it("applies a fixed backend deadline", async () => {
    vi.useFakeTimers({ toFake: ["setTimeout"] });
    try {
      const fetchImpl = vi.fn(() => new Promise<Response>(() => undefined));
      const pending = verifyImageWithBackend(image, settings, {
        fetchImpl: fetchImpl as unknown as typeof fetch,
      });
      const expected = expect(pending).rejects.toMatchObject({
        code: "request_timeout",
      });
      await vi.advanceTimersByTimeAsync(30_001);
      await expected;
    } finally {
      vi.useRealTimers();
    }
  });

  it("preserves explicit user cancellation separately from a deadline", async () => {
    const controller = new AbortController();
    const fetchImpl = vi.fn(() => new Promise<Response>(() => undefined));
    const pending = verifyImageWithBackend(image, settings, {
      signal: controller.signal,
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });
    controller.abort(USER_CANCELLED_REASON);
    await expect(pending).rejects.toMatchObject({ code: "user_cancelled" });
  });
});
