import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
  CacheLookupRequestSchema,
  LocalVerificationCacheRecordSchema,
  RESULT_SCHEMA_VERSION,
  VERIFICATION_POLICY_VERSION,
  deriveCacheNamespace,
  sha256Hex,
  type NormalizedProvenanceResult,
} from "@provenance-lens/shared";

import { defaultExpiryForVerdict, isCacheableResult } from "../../src/cache.js";

import { describe, expect, it } from "vitest";

const requestId = "123e4567-e89b-42d3-a456-426614174000";

function result(
  verdict: NormalizedProvenanceResult["verdict"],
): NormalizedProvenanceResult {
  return {
    verdict,
    summary:
      verdict === "openai_signal_detected"
        ? "Detected signals: SynthID."
        : verdict === "no_supported_openai_signal"
          ? "No supported OpenAI provenance signal was detected. This does not prove that the image is human-made or that it was not generated by another AI system."
          : "The image could not be verified.",
    signals:
      verdict === "openai_signal_detected"
        ? [
            {
              type: "synthid",
              outcome: "detected",
              validationState: null,
              issuer: null,
              model: null,
              generatedAt: null,
            },
          ]
        : [],
    warnings: [],
    checkedAt: "2026-09-01T10:00:00.000Z",
    requestId,
  };
}

function cacheRecord(value: NormalizedProvenanceResult) {
  return {
    namespace: "a".repeat(64),
    imageSha256: "b".repeat(64),
    byteLength: 3,
    validatedMimeType: "image/png",
    verdict: value.verdict,
    result: value,
    originallyCheckedAt: "2026-09-01T10:00:00.000Z",
    lastAccessedAt: "2026-09-01T10:01:00.000Z",
    expiresAt: "2099-09-08T10:00:00.000Z",
    verificationPolicyVersion: VERIFICATION_POLICY_VERSION,
    resultSchemaVersion: RESULT_SCHEMA_VERSION,
  };
}

describe("extension cache contracts", () => {
  it.each(["openai_signal_detected", "no_supported_openai_signal"] as const)(
    "accepts the successful %s outcome",
    (verdict) => {
      const value = result(verdict);
      expect(isCacheableResult(value)).toBe(true);
      expect(
        LocalVerificationCacheRecordSchema.safeParse(cacheRecord(value))
          .success,
      ).toBe(true);
      expect(defaultExpiryForVerdict(verdict)).not.toBeNull();
    },
  );

  it("never caches indeterminate results", () => {
    const value = result("indeterminate");
    expect(isCacheableResult(value)).toBe(false);
    expect(defaultExpiryForVerdict(value.verdict)).toBeNull();
    expect(
      LocalVerificationCacheRecordSchema.safeParse(cacheRecord(value)).success,
    ).toBe(false);
  });

  it("keys exact bytes, so one-byte changes and alternate encodings miss", async () => {
    const original = new Uint8Array([1, 2, 3]);
    const oneByteDifferent = new Uint8Array([1, 2, 4]);
    const encodings = await Promise.all(
      ["image-fixture.png", "image-fixture.jpg", "image-fixture.webp"].map(
        async (filename) =>
          new Uint8Array(
            await readFile(resolve(process.cwd(), "tests/fixtures", filename)),
          ),
      ),
    );
    const [png, jpeg, webp] = encodings;
    if (!png || !jpeg || !webp) throw new Error("Missing image fixture");
    const [pngHash, jpegHash, webpHash] = await Promise.all(
      [png, jpeg, webp].map((bytes) => sha256Hex(bytes)),
    );
    const originalHash = await sha256Hex(original);
    await expect(sha256Hex(oneByteDifferent)).resolves.not.toBe(originalHash);
    expect(new Set([pngHash, jpegHash, webpHash]).size).toBe(3);
  });

  it("derives independent namespaces for backend origin and identity", async () => {
    const first = await deriveCacheNamespace(
      "https://verify-a.example",
      "client-one",
    );
    const second = await deriveCacheNamespace(
      "https://verify-b.example",
      "client-one",
    );
    const third = await deriveCacheNamespace(
      "https://verify-a.example",
      "client-two",
    );
    expect(new Set([first, second, third]).size).toBe(3);
  });

  it("keeps lookup metadata free of URLs", () => {
    const parsed = CacheLookupRequestSchema.parse({
      imageSha256: "c".repeat(64),
      byteLength: 3,
      validatedMimeType: "image/webp",
      verificationPolicyVersion: VERIFICATION_POLICY_VERSION,
    });
    expect(parsed).not.toHaveProperty("url");
  });
});
