import "fake-indexeddb/auto";

import sharp from "sharp";

import {
  RESULT_SCHEMA_VERSION,
  VERIFICATION_POLICY_VERSION,
  sha256Hex,
  type CacheMetadata,
  type ExtensionSettings,
  type NormalizedProvenanceResult,
} from "@provenance-lens/shared";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import {
  clearVerificationCache,
  findLocalCache,
  saveLocalCache,
} from "../../src/cache.js";

const settings: ExtensionSettings = {
  verificationMode: "api",
  acknowledgedVerificationModes: ["api"],
  backendBaseUrl: "https://verify.example",
  clientToken: "client-one",
  historyRetention: 20,
  screenshotFallbackEnabled: false,
  includePageTitle: true,
  debugMode: false,
  localCacheLimit: 10,
  disclosureVersion: 2,
};

function result(
  verdict: "openai_signal_detected" | "no_supported_openai_signal",
  index = 0,
): NormalizedProvenanceResult {
  return {
    verdict,
    summary:
      verdict === "openai_signal_detected"
        ? "Detected signals: SynthID."
        : "No supported OpenAI provenance signal was detected. This does not prove that the image is human-made or that it was not generated by another AI system.",
    signals:
      verdict === "openai_signal_detected"
        ? [
            {
              type: "synthid",
              outcome: "detected",
              validationState: null,
              issuer: null,
              model: null,
              generatedAt: null,
            },
          ]
        : [],
    warnings: [],
    checkedAt: "2026-09-01T10:00:00.000Z",
    requestId: `123e4567-e89b-42d3-a456-42661417400${index % 10}`,
  };
}

function cache(expiresAt = "2099-09-08T10:00:00.000Z"): CacheMetadata {
  return {
    source: "fresh",
    originallyCheckedAt: "2026-09-01T10:00:00.000Z",
    expiresAt,
    verificationPolicyVersion: VERIFICATION_POLICY_VERSION,
    resultSchemaVersion: RESULT_SCHEMA_VERSION,
  };
}

async function metadata(index: number) {
  const bytes = new Uint8Array([137, 80, 78, 71, index & 0xff]);
  return {
    imageSha256: await sha256Hex(bytes),
    byteLength: bytes.byteLength,
    validatedMimeType: "image/png" as const,
    verificationPolicyVersion: VERIFICATION_POLICY_VERSION,
  };
}

describe("IndexedDB local verification cache", () => {
  beforeEach(async () => {
    await clearVerificationCache();
  });

  afterEach(async () => {
    await clearVerificationCache();
  });

  it("stores and returns both detected and no-signal results", async () => {
    const detectedMetadata = await metadata(1);
    const noSignalMetadata = await metadata(2);
    await saveLocalCache(
      settings,
      detectedMetadata,
      result("openai_signal_detected", 1),
      cache(),
    );
    await saveLocalCache(
      settings,
      noSignalMetadata,
      result("no_supported_openai_signal", 2),
      cache(),
    );

    await expect(
      findLocalCache(settings, detectedMetadata),
    ).resolves.toMatchObject({
      result: { verdict: "openai_signal_detected" },
      cache: { source: "local_cache" },
    });
    await expect(
      findLocalCache(settings, noSignalMetadata),
    ).resolves.toMatchObject({
      result: { verdict: "no_supported_openai_signal" },
      cache: { source: "local_cache" },
    });
  });

  it("expires records according to the server-provided expiration", async () => {
    const item = await metadata(3);
    await saveLocalCache(
      settings,
      item,
      result("openai_signal_detected", 3),
      cache("2026-09-01T10:00:00.001Z"),
    );
    await expect(findLocalCache(settings, item)).resolves.toBeNull();
  });

  it("enforces a ten-record LRU limit and preserves a touched older entry", async () => {
    vi.useFakeTimers({ toFake: ["Date"] });
    try {
      const baseTime = Date.parse("2026-09-01T10:00:00.000Z");
      const records = [];
      for (let index = 0; index < 10; index += 1) {
        vi.setSystemTime(baseTime + index * 1_000);
        const item = await metadata(10 + index);
        records.push(item);
        await saveLocalCache(
          settings,
          item,
          result("openai_signal_detected", index),
          cache(),
        );
      }

      const leastRecentlyUsed = records[0];
      const touchedOlderEntry = records[1];
      if (!leastRecentlyUsed || !touchedOlderEntry)
        throw new Error("Missing test records");
      vi.setSystemTime(baseTime + 20_000);
      await expect(
        findLocalCache(settings, touchedOlderEntry),
      ).resolves.not.toBeNull();

      vi.setSystemTime(baseTime + 30_000);
      const eleventh = await metadata(20);
      await saveLocalCache(
        settings,
        eleventh,
        result("openai_signal_detected", 20),
        cache(),
      );

      await expect(
        findLocalCache(settings, leastRecentlyUsed),
      ).resolves.toBeNull();
      await expect(
        findLocalCache(settings, touchedOlderEntry),
      ).resolves.not.toBeNull();
      await expect(findLocalCache(settings, eleventh)).resolves.not.toBeNull();
    } finally {
      vi.useRealTimers();
    }
  });

  it("isolates records by backend origin and client identity", async () => {
    const item = await metadata(4);
    await saveLocalCache(
      settings,
      item,
      result("openai_signal_detected", 4),
      cache(),
    );
    await expect(
      findLocalCache({ ...settings, clientToken: "client-two" }, item),
    ).resolves.toBeNull();
    await expect(
      findLocalCache(
        { ...settings, backendBaseUrl: "https://other.example" },
        item,
      ),
    ).resolves.toBeNull();
  });

  it("misses a visually identical image after byte-level re-encoding", async () => {
    const pixels = Buffer.alloc(16 * 16 * 4);
    for (let index = 0; index < pixels.length; index += 4) {
      pixels[index] = (index / 4) % 251;
      pixels[index + 1] = 96;
      pixels[index + 2] = 192;
      pixels[index + 3] = 255;
    }
    const raw = { width: 16, height: 16, channels: 4 as const };
    const [firstEncoding, secondEncoding] = await Promise.all([
      sharp(pixels, { raw })
        .png({ compressionLevel: 0, adaptiveFiltering: false })
        .toBuffer(),
      sharp(pixels, { raw })
        .png({ compressionLevel: 9, adaptiveFiltering: true })
        .toBuffer(),
    ]);
    const [firstDecoded, secondDecoded] = await Promise.all([
      sharp(firstEncoding).raw().toBuffer(),
      sharp(secondEncoding).raw().toBuffer(),
    ]);
    expect(firstDecoded).toEqual(secondDecoded);

    const firstMetadata = {
      imageSha256: await sha256Hex(firstEncoding),
      byteLength: firstEncoding.byteLength,
      validatedMimeType: "image/png" as const,
      verificationPolicyVersion: VERIFICATION_POLICY_VERSION,
    };
    const secondMetadata = {
      ...firstMetadata,
      imageSha256: await sha256Hex(secondEncoding),
      byteLength: secondEncoding.byteLength,
    };
    expect(secondMetadata.imageSha256).not.toBe(firstMetadata.imageSha256);

    await saveLocalCache(
      settings,
      firstMetadata,
      result("openai_signal_detected", 6),
      cache(),
    );
    await expect(findLocalCache(settings, secondMetadata)).resolves.toBeNull();
  });

  it("clears records independently of history storage", async () => {
    const item = await metadata(5);
    await saveLocalCache(
      settings,
      item,
      result("no_supported_openai_signal", 5),
      cache(),
    );
    await clearVerificationCache();
    await expect(findLocalCache(settings, item)).resolves.toBeNull();
  });
});
