import type { NormalizedProvenanceResult } from "@provenance-lens/shared";
import { describe, expect, it } from "vitest";

import {
  detectedToastCopy,
  errorToastCopy,
  matchesResultToastBinding,
  noSignalToastCopy,
  removePageResultToastBindings,
  removeResultToastBinding,
  resultDetailsUrl,
  upsertResultToastBinding,
} from "../../src/notifications.js";

const baseResult: NormalizedProvenanceResult = {
  verdict: "openai_signal_detected",
  summary: "Detected signals: C2PA and SynthID.",
  signals: [
    {
      type: "c2pa",
      outcome: "detected",
      validationState: "trusted",
      issuer: null,
      model: null,
      generatedAt: null,
    },
    {
      type: "synthid",
      outcome: "detected",
      validationState: null,
      issuer: null,
      model: null,
      generatedAt: null,
    },
  ],
  warnings: [],
  checkedAt: "2026-09-01T10:00:00.000Z",
  requestId: "123e4567-e89b-42d3-a456-426614174000",
};

describe("toast copies and result links", () => {
  it("describes detected signals without exposing arbitrary page data", () => {
    expect(detectedToastCopy(baseResult)).toEqual({
      title: "OpenAI provenance detected",
      message: "Detected signals: C2PA and SynthID.",
    });
  });

  it("keeps the no-signal limitation explicit", () => {
    expect(noSignalToastCopy()).toEqual({
      title: "No supported OpenAI signal detected",
      message:
        "This does not prove that the image is human-made or that it was not generated by another AI system.",
    });
  });

  it("keeps errors and result details on the extension origin", () => {
    expect(errorToastCopy("Backend unavailable").message).toBe(
      "Backend unavailable",
    );
    expect(
      resultDetailsUrl("chrome-extension://test-id/details.html", "123"),
    ).toBe("chrome-extension://test-id/details.html?id=123");
  });

  it("opens details only for the exact bound result document", () => {
    const binding = {
      resultId: "123e4567-e89b-42d3-a456-426614174000",
      sessionToken: "223e4567-e89b-42d3-a456-426614174000",
      tabId: 7,
      frameId: 3,
      documentId: "document-1",
    };
    const request = {
      resultId: binding.resultId,
      sessionToken: binding.sessionToken,
    };
    const sender = {
      tabId: binding.tabId,
      frameId: binding.frameId,
      documentId: binding.documentId,
    };
    expect(matchesResultToastBinding(binding, request, sender)).toBe(true);
    expect(
      matchesResultToastBinding(binding, request, {
        ...sender,
        documentId: "navigated-document",
      }),
    ).toBe(false);
    expect(
      matchesResultToastBinding(binding, request, {
        ...sender,
        frameId: 0,
      }),
    ).toBe(false);
    expect(
      matchesResultToastBinding(binding, request, {
        ...sender,
        tabId: undefined,
      }),
    ).toBe(false);
    expect(
      matchesResultToastBinding(
        binding,
        { ...request, resultId: "323e4567-e89b-42d3-a456-426614174000" },
        sender,
      ),
    ).toBe(false);
    expect(
      matchesResultToastBinding(
        binding,
        {
          ...request,
          sessionToken: "423e4567-e89b-42d3-a456-426614174000",
        },
        sender,
      ),
    ).toBe(false);
  });

  it("keeps a bounded single result binding per document", () => {
    const first = {
      resultId: "123e4567-e89b-42d3-a456-426614174000",
      sessionToken: "223e4567-e89b-42d3-a456-426614174000",
      tabId: 7,
      frameId: 3,
      documentId: "document-1",
    };
    const replacement = {
      ...first,
      resultId: "323e4567-e89b-42d3-a456-426614174000",
      sessionToken: "423e4567-e89b-42d3-a456-426614174000",
    };
    const otherDocument = {
      ...first,
      resultId: "523e4567-e89b-42d3-a456-426614174000",
      sessionToken: "623e4567-e89b-42d3-a456-426614174000",
      documentId: "document-2",
    };
    const bindings = upsertResultToastBinding(
      upsertResultToastBinding([first], otherDocument, 2),
      replacement,
      2,
    );
    expect(bindings).toEqual([otherDocument, replacement]);
    expect(removeResultToastBinding(bindings, replacement)).toEqual([
      otherDocument,
    ]);
    expect(
      removePageResultToastBindings(bindings, {
        tabId: otherDocument.tabId,
        frameId: otherDocument.frameId,
        documentId: otherDocument.documentId,
      }),
    ).toEqual([replacement]);
  });
});
