import {
  CacheLookupResponseSchema,
  CacheLookupRequestSchema,
  LocalVerificationCacheRecordSchema,
  RESULT_SCHEMA_VERSION,
  VERIFICATION_POLICY_VERSION,
  VerificationResponseSchema,
  deriveCacheNamespace,
  sha256Hex,
  type NormalizedProvenanceResult,
} from "../src/index.js";

const requestId = "123e4567-e89b-42d3-a456-426614174000";
const detected: NormalizedProvenanceResult = {
  verdict: "openai_signal_detected",
  summary: "Detected signals: SynthID.",
  signals: [
    {
      type: "synthid",
      outcome: "detected",
      validationState: null,
      issuer: null,
      model: null,
      generatedAt: null,
    },
  ],
  warnings: [],
  checkedAt: "2026-09-01T10:00:00.000Z",
  requestId,
};

const noSignal: NormalizedProvenanceResult = {
  verdict: "no_supported_openai_signal",
  summary:
    "No supported OpenAI provenance signal was detected. This does not prove that the image is human-made or that it was not generated by another AI system.",
  signals: [
    {
      type: "synthid",
      outcome: "not_detected",
      validationState: null,
      issuer: null,
      model: null,
      generatedAt: null,
    },
  ],
  warnings: [],
  checkedAt: "2026-09-01T10:00:00.000Z",
  requestId,
};

function cacheRecord(result: NormalizedProvenanceResult) {
  return {
    namespace: "a".repeat(64),
    imageSha256: "b".repeat(64),
    byteLength: 123,
    validatedMimeType: "image/png",
    verdict: result.verdict,
    result,
    originallyCheckedAt: "2026-09-01T10:00:00.000Z",
    lastAccessedAt: "2026-09-01T10:01:00.000Z",
    expiresAt: "2026-09-08T10:00:00.000Z",
    verificationPolicyVersion: VERIFICATION_POLICY_VERSION,
    resultSchemaVersion: RESULT_SCHEMA_VERSION,
  };
}

describe("exact-byte cache contracts", () => {
  it("calculates SHA-256 from the exact byte sequence", async () => {
    const bytes = new TextEncoder().encode("abc");
    await expect(sha256Hex(bytes)).resolves.toBe(
      "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
    );
  });

  it("makes a one-byte difference a cache miss", async () => {
    const first = await sha256Hex(new Uint8Array([1, 2, 3]));
    const second = await sha256Hex(new Uint8Array([1, 2, 4]));
    expect(first).not.toBe(second);
  });

  it("does not hash a base64 representation in place of the bytes", async () => {
    const bytes = new Uint8Array([137, 80, 78, 71]);
    const bytesHash = await sha256Hex(bytes);
    const base64TextHash = await sha256Hex(
      new TextEncoder().encode("iVBORw=="),
    );
    expect(bytesHash).not.toBe(base64TextHash);
  });

  it("isolates local cache namespaces by backend origin and identity", async () => {
    const first = await deriveCacheNamespace(
      "https://verify-a.example",
      "client-one",
    );
    const second = await deriveCacheNamespace(
      "https://verify-b.example",
      "client-one",
    );
    const third = await deriveCacheNamespace(
      "https://verify-a.example",
      "client-two",
    );
    expect(new Set([first, second, third]).size).toBe(3);
  });

  it.each([detected, noSignal])(
    "accepts both successful verdicts in the cache",
    (result) => {
      expect(
        LocalVerificationCacheRecordSchema.safeParse(cacheRecord(result))
          .success,
      ).toBe(true);
    },
  );

  it("rejects indeterminate cache records", () => {
    const indeterminate: NormalizedProvenanceResult = {
      ...noSignal,
      verdict: "indeterminate",
      summary: "The image could not be verified.",
    };
    expect(
      LocalVerificationCacheRecordSchema.safeParse(cacheRecord(indeterminate))
        .success,
    ).toBe(false);
  });

  it("rejects an indeterminate backend cache hit", () => {
    const indeterminate: NormalizedProvenanceResult = {
      ...noSignal,
      verdict: "indeterminate",
      summary: "The image could not be verified.",
    };
    expect(
      CacheLookupResponseSchema.safeParse({
        hit: true,
        result: indeterminate,
        originallyCheckedAt: "2026-09-01T10:00:00.000Z",
        expiresAt: "2026-09-08T10:00:00.000Z",
        verificationPolicyVersion: VERIFICATION_POLICY_VERSION,
        resultSchemaVersion: RESULT_SCHEMA_VERSION,
      }).success,
    ).toBe(false);
  });

  it("rejects a legacy cached positive without a reliable detected signal", () => {
    const unreliable = {
      ...detected,
      signals: [
        {
          type: "c2pa" as const,
          outcome: "detected" as const,
          validationState: "not_present" as const,
          issuer: null,
          model: null,
          generatedAt: null,
        },
      ],
    };

    expect(
      LocalVerificationCacheRecordSchema.safeParse(cacheRecord(unreliable))
        .success,
    ).toBe(false);
    expect(
      CacheLookupResponseSchema.safeParse({
        hit: true,
        result: unreliable,
        originallyCheckedAt: unreliable.checkedAt,
        expiresAt: "2026-09-08T10:00:00.000Z",
        verificationPolicyVersion: VERIFICATION_POLICY_VERSION,
        resultSchemaVersion: RESULT_SCHEMA_VERSION,
      }).success,
    ).toBe(false);
  });

  it("requires cache metadata only for cacheable verification results", () => {
    const metadata = {
      source: "fresh",
      originallyCheckedAt: "2026-09-01T10:00:00.000Z",
      expiresAt: "2026-09-08T10:00:00.000Z",
      verificationPolicyVersion: VERIFICATION_POLICY_VERSION,
      resultSchemaVersion: RESULT_SCHEMA_VERSION,
    };
    expect(
      VerificationResponseSchema.safeParse({
        result: detected,
        cache: metadata,
      }).success,
    ).toBe(true);
    expect(
      VerificationResponseSchema.safeParse({
        result: { ...noSignal, verdict: "indeterminate" },
        cache: metadata,
      }).success,
    ).toBe(false);
    expect(
      VerificationResponseSchema.safeParse({ result: detected, cache: null })
        .success,
    ).toBe(false);
  });

  it("rejects cache metadata whose expiry does not follow the check", () => {
    expect(
      LocalVerificationCacheRecordSchema.safeParse({
        ...cacheRecord(detected),
        expiresAt: "2026-09-01T09:59:59.000Z",
      }).success,
    ).toBe(false);
  });

  it("validates tenant-safe backend lookup metadata without URLs", () => {
    const parsed = CacheLookupRequestSchema.parse({
      imageSha256: "c".repeat(64),
      byteLength: 123,
      validatedMimeType: "image/webp",
      verificationPolicyVersion: VERIFICATION_POLICY_VERSION,
    });
    expect(parsed).not.toHaveProperty("url");
  });
});
